In [31]:
import tensorflow as tf

In [32]:
## tensorflow version
print("Tensorflow version",tf.__version__)

Tensorflow version 2.18.0


In [33]:
## load datasets
mnist = tf.keras.datasets.mnist

In [34]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [35]:
## building a machine learning model
input_shape = X_train[0].shape
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape = input_shape),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

/usr/local/python/3.12.1/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [36]:
# predictions
predictions = model(X_train[:1]).numpy()
predictions

array([[ -46.457817, -151.84863 ,  156.64471 ,  -56.361523,    7.431802,
         -92.42943 ,   93.97866 ,   97.07191 ,  -32.252975,  -66.95527 ]],
      dtype=float32)

In [37]:
# this will convert these logits to probabilit for rach classes
tf.nn.softmax(predictions).numpy()

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 6.0880562e-28, 1.3423276e-26,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [38]:
## loss fucntion: define a loss function for the training using
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [39]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(249.07414)

In [40]:
## compile the model
model.compile(optimizer='adam', loss = loss_fn, metrics=['accuracy'])

In [41]:
## fit the model for the training
history = model.fit(X_train, y_train, epochs=10)

Epoch 1/10


2024-11-13 19:45:24.922433: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 47040000 exceeds 10% of free system memory.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.7023 - loss: 8.7815
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8341 - loss: 0.6262
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8680 - loss: 0.4854
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8867 - loss: 0.4174
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.8947 - loss: 0.3936
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9034 - loss: 0.3786
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.9057 - loss: 0.3634
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9099 - loss: 0.3509
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.9105 - loss: 0.3407
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9114 - loss: 0.3440


In [45]:
## it will check the models performace
loss, accuracy = model.evaluate(X_test, y_test, verbose=2)
print("loss is:", loss)
print("accuracy: ", accuracy)

313/313 - 0s - 948us/step - accuracy: 0.9492 - loss: 0.2720
loss is: 0.27195537090301514
accuracy:  0.9491999745368958


In [46]:
probability_model = tf.keras.Sequential([
    tf.keras.layers.Softmax()
])

In [51]:
probability_model(X_test[:5])

<tf.Tensor: shape=(5, 28, 28), dtype=float32, numpy=
array([[[0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428],
        [0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428],
        [0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428]],

       [[0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428],
        [0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428],
        [0.03571428, 0.03571428, 0.03571428, ..., 0.03571428,
         0.03571428, 0.03571428],
        ...,
        [0.03571428, 0.03571428, 0.03571428, ..., 0.035